### ISSUE TITLE
Node's NIC type is empty string caused docker0 show up

### ISSUE THREAD

**Issue by John-Lin** [linkernetworks/vortex#251]
<img width="705" alt="screen shot 2018-08-17 at 1 14 01 am" src="https://user-images.githubusercontent.com/4214069/44223686-e43d1f00-a1ba-11e8-9bc8-c421c6841454.png">

JSON from backend

<img width="624" alt="screen shot 2018-08-17 at 1 11 55 am" src="https://user-images.githubusercontent.com/4214069/44223647-c2439c80-a1ba-11e8-9a66-56b74e69b797.png">

**Comment by WakeupTsai** [comment]
I can not reproduce this bug. Did you encounter this bug before upgrade vortex server to latest release?

**Comment by John-Lin** [comment]
refer to #254
