### ISSUE TITLE
Namespace list not showing

### ISSUE THREAD

**Issue by John-Lin** [linkernetworks/vortex#252]
<img width="1463" alt="screen shot 2018-08-17 at 1 18 39 am" src="https://user-images.githubusercontent.com/4214069/44223945-aa204d00-a1bb-11e8-93d4-1832af253ef0.png">
<img width="578" alt="screen shot 2018-08-17 at 1 18 52 am" src="https://user-images.githubusercontent.com/4214069/44223946-aa204d00-a1bb-11e8-917e-249d366469db.png">

**Comment by chenyunchen** [comment]
Fix this in the latest develop branch.
